### ISSUE TITLE
Improve simple pattern detection engine

### ISSUE THREAD

**Issue by VictorABoye** [JonasKaad/BachelorProject#35]
We could improve the simple pattern detection engine in a couple ways.
- [x] Ignore points with altitude 0
- [x] Check that the inversions are close enough together to be part of a holding pattern
- [x] Check if the inversion points are close to the general flight level and speed of general holding patterns

**Comment by VictorABoye** [comment]
![Image](https://user-images.githubusercontent.com/35064405/228453834-3a4ef7a7-feb2-4db5-ac55-03db56220644.png)

We could also look into getting the rest of the data that we want for the db entries for holding patterns, like:
* Fix point
* Laps
* Direction
* Leg Distance
* Altitude

**Comment by JonasKaad** [comment]
- Ask NavDB for what the closest airport is based on the last `LAT LON`, in order to find airport in case the flight doesn't have one.
- Analyze on timestamp to get laps, so two concurrent points don't count as different laps.
- Also check that inversions are far enough apart. (Could maybe use `page 1-6-1-7` (pdf p. `145`) from `ICAO Document 8168`)
- Check the leg distance, should not be too long. Use timestamps (max is 1min30sec)
	- Check 5 points to see if it is still going the same direction.
- Take a look at altitude in regards to holding patterns. (What is the minimum flight level?)
- Look at direction (If going LEFT => should be negative. Going RIGHT => should be positive). Should be done on all inversion points.
